
import java.security.MessageDigest;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class Home extends javax.swing.JFrame {
    String name,id;
    Requests ob;
    String posts[]=new String[100];
    String names[]= new String[100]; // Array ro hold names of users who have posted something
    java.sql.Connection con=new SQL_Connection().getConnection();
    int count=0;
    /**
     * Creates new form Home
     */
    public void setter(String name1, String id1)
    {
        name=name1;
        id=id1;
        home_greet.setText("Hi " + name);
        
        //Code for showing text areas with posts
        try
        {
        PreparedStatement pst1=con.prepareStatement("select name, Post from registration inner join posts on registration.id=posts.user_id where user_id in (select from_id from requests where active=0 and to_id=?); ");
        
        pst1.setString(1,id);
        
        
        ResultSet rs=pst1.executeQuery();
        while(rs.next())
        {
            System.out.println(rs.getString("name")+"    :   "+rs.getString("Post"));
            names[count]=rs.getString("name");
            posts[count++]=rs.getString("Post");
        }
        
        PreparedStatement pst2=con.prepareStatement("select name, Post from registration inner join posts on registration.id=posts.user_id where user_id in (select to_id from requests where active=0 and from_id=?); ");
        pst2.setString(1,id);
        
        
        ResultSet rs2=pst2.executeQuery();
        
        while(rs2.next())
        {
            
            names[count]=rs2.getString("name");
            posts[count++]=rs2.getString("Post");
        }
        }   
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
        switch(count-1)
        {
            case 1 : post1.setVisible(true);
                    post1.setText(names[1]+": \n" + posts[1]);
                    
                    
                    
            case 0 : post0.setVisible(true);
                    post0.setText(names[0]+": \n" + posts[0]);
                    
                    
        }
        
    }
   public Home() {
        initComponents();
        post0.setVisible(false);
        post1.setVisible(false);
        post0.setEditable(false);
        post1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        home_greet = new javax.swing.JLabel();
        search_box = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        post0 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        post1 = new javax.swing.JTextArea();
        post_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        my_post = new javax.swing.JTextArea();
        post_status = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Show Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("POSTS");

        post0.setColumns(20);
        post0.setRows(5);
        jScrollPane1.setViewportView(post0);

        post1.setColumns(20);
        post1.setRows(5);
        jScrollPane2.setViewportView(post1);

        post_button.setText("POST");
        post_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_buttonActionPerformed(evt);
            }
        });

        my_post.setColumns(20);
        my_post.setRows(5);
        jScrollPane3.setViewportView(my_post);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(home_greet, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(post_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(post_status, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_greet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(post_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(post_status, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        Search obj=new Search();
        String search_token=search_box.getText();
        
        try
        {
        int count=-1;
        String name[]=new String[100];
        String place[]=new String[100];
        String requestTo_id[]=new String[100];
        PreparedStatement pst=con.prepareStatement("select * from registration where id=? or name=? or number=?");
        pst.setString(1,search_token);
        pst.setString(2,search_token);
        pst.setString(3,search_token);
        ResultSet rs=pst.executeQuery();
        while(rs.next())
        {
          count++;
          name[count]=rs.getString("name");
          place[count]=rs.getString("place");
          requestTo_id[count]=rs.getString("id");
          obj.setVisible(true);
        }
        obj.setter(count,name,place,id,requestTo_id);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ob=new Requests();
        
        //this.setVisible(false);
        ob.setVisible(true);
        ob.setter(id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void post_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_buttonActionPerformed
        // TODO add your handling code here:
        String p=my_post.getText();
        try
        {
        
        
        PreparedStatement pst=con.prepareStatement("insert into posts (user_id,post) values (?,?)");
        pst.setString(1, id);
        pst.setString(2, p);
        
        int status=pst.executeUpdate();
        post_status.setText("Posted Successfully");
        my_post.setText("");
        }
        catch(Exception e)
        {
            post_status.setText(e.toString());
            //System.out.println(e.toString());
        }
    }//GEN-LAST:event_post_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home_greet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextArea my_post;
    private javax.swing.JTextArea post0;
    private javax.swing.JTextArea post1;
    private javax.swing.JButton post_button;
    private javax.swing.JLabel post_status;
    private javax.swing.JTextField search_box;
    private javax.swing.JButton search_button;
    // End of variables declaration//GEN-END:variables
}
