
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class Requests extends javax.swing.JFrame {
    String id;
    int count=0;
    String place[]=new String[10];
    String name[]=new String[10];
    String from_Id[]=new String[10];
    /**
     * Creates new form Requests
     * 
     */
     java.sql.Connection con=new SQL_Connection().getConnection();
    public Requests() {
        initComponents();
        accept0.setVisible(false);
        accept1.setVisible(false);
        accept2.setVisible(false);
        accept3.setVisible(false);
        accept4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accept0 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        accept1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        accept2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        name0 = new javax.swing.JLabel();
        place0 = new javax.swing.JLabel();
        accept3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        accept4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        name1 = new javax.swing.JLabel();
        place1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        place2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        place3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        place4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accept0.setText("Accept Request");
        accept0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept0ActionPerformed(evt);
            }
        });

        accept1.setText("jButton2");
        accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept1ActionPerformed(evt);
            }
        });

        accept2.setText("jButton3");
        accept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept2ActionPerformed(evt);
            }
        });

        name0.setText("jLabel1");

        place0.setText("jLabel2");

        accept3.setText("jButton1");
        accept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept3ActionPerformed(evt);
            }
        });

        accept4.setText("jButton4");
        accept4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept4ActionPerformed(evt);
            }
        });

        name1.setText("jLabel1");

        place1.setText("jLabel2");

        name2.setText("jLabel3");

        place2.setText("jLabel4");

        name3.setText("jLabel5");

        place3.setText("jLabel6");

        name4.setText("jLabel7");

        place4.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(place0)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accept0)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name4)
                    .addComponent(place4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept4)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name1)
                    .addComponent(place1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(accept1)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name2)
                    .addComponent(place2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept2)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name3)
                    .addComponent(place3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accept3)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name0))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(accept0)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(place0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(accept1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place1)))
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(accept2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(name2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(place2)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(accept3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(place3)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accept4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(place4))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accept0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept0ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst=con.prepareStatement("update requests set active=0 where (from_id=? and to_id=?)");
        pst.setString(1, from_Id[0]);
        pst.setString(2, id);
       
        int status=pst.executeUpdate();
        accept0.setText("You are now friends");
        accept0.setEnabled(false);
        }
        catch(Exception e)
        {
            accept0.setText(e.toString());
        }
    }//GEN-LAST:event_accept0ActionPerformed

    private void accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept1ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst=con.prepareStatement("update requests set active=0 where (from_id=? and to_id=?)");
        pst.setString(1, from_Id[1]);
        pst.setString(2, id);
       
        int status=pst.executeUpdate();
        accept1.setText("You are now friends");
        accept1.setEnabled(false);
        }
        catch(Exception e)
        {
            accept1.setText(e.toString());
        }
    }//GEN-LAST:event_accept1ActionPerformed

    private void accept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept2ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst=con.prepareStatement("update requests set active=0 where (from_id=? and to_id=?)");
        pst.setString(1, from_Id[2]);
        pst.setString(2, id);
       
        int status=pst.executeUpdate();
        accept2.setText("You are now friends");
        accept2.setEnabled(false);
        }
        catch(Exception e)
        {
            accept2.setText(e.toString());
        }
    }//GEN-LAST:event_accept2ActionPerformed

    private void accept3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept3ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst=con.prepareStatement("update requests set active=0 where (from_id=? and to_id=?)");
        pst.setString(1, from_Id[3]);
        pst.setString(2, id);
       
        int status=pst.executeUpdate();
        accept3.setText("You are now friends");
        accept3.setEnabled(false);
        }
        catch(Exception e)
        {
            accept3.setText(e.toString());
        }
    }//GEN-LAST:event_accept3ActionPerformed

    private void accept4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept4ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst=con.prepareStatement("update requests set active=0 where (from_id=? and to_id=?)");
        pst.setString(1, from_Id[4]);
        pst.setString(2, id);
       
        int status=pst.executeUpdate();
        accept4.setText("You are now friends");
        accept4.setEnabled(false);
        }
        catch(Exception e)
        {
            accept4.setText(e.toString());
        }
    }//GEN-LAST:event_accept4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setter(String id1)
    {
        id=id1;
        
        try
        {
        PreparedStatement pst1=con.prepareStatement("select name, place, id from registration where id in(select from_id from requests where to_id=? and active=1)");
        pst1.setString(1,id);
        
        ResultSet rs=pst1.executeQuery();
        while(rs.next())
        {
            
            /*System.out.println("#########");
            exists[i]=1;
            request_status[i]=rs.getInt("active");*/
            
            name[count]=rs.getString("name");
            place[count]=rs.getString("place");
            from_Id[count]=rs.getString("id");
            count++;
        }
        
        }   
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        //reg_status.setText("Registration Successful");
        
        
        switch(count-1)
        {
            case 4 : accept4.setVisible(true);
                    name4.setText(name[4]);
                    place4.setText(place[4]);
            case 3 : accept3.setVisible(true);
                    name3.setText(name[3]);
                    place3.setText(place[3]);
            case 2 : accept2.setVisible(true);
                    name2.setText(name[2]);
                    place2.setText(place[2]);
            case 1 : accept1.setVisible(true);
                    name1.setText(name[1]);
                    place1.setText(place[1]);
                    System.out.println("***********");
            case 0 : accept0.setVisible(true);
                    name0.setText(name[0]);
                    place0.setText(place[0]);
                    System.out.println("***********");
                    
            
                
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept0;
    private javax.swing.JButton accept1;
    private javax.swing.JButton accept2;
    private javax.swing.JButton accept3;
    private javax.swing.JButton accept4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel name0;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel place0;
    private javax.swing.JLabel place1;
    private javax.swing.JLabel place2;
    private javax.swing.JLabel place3;
    private javax.swing.JLabel place4;
    // End of variables declaration//GEN-END:variables
}
