
import java.security.MessageDigest;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class Search extends javax.swing.JFrame {
     String id;
     String requestTo_id[];
      java.sql.Connection con=new SQL_Connection().getConnection();
    /**
     * Creates new form Search
     */
    public void setter(int count,String name[], String place[],String id1, String requestTo_id1[])
    {
        id=id1;
        requestTo_id=requestTo_id1;
        int exists[]=new int[5];
        int request_status[]=new int[5];
        for(int i=0;i<=count;i++)
        {
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where (from_id=? and to_id=?) or (from_id=? and to_id=?)");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[i]);
        pst1.setString(3,requestTo_id[i]);
        pst1.setString(4,id);
        ResultSet rs=pst1.executeQuery();
        if(rs.next())
        {
            System.out.println("#########");
            exists[i]=1;
            request_status[i]=rs.getInt("active");
        }
        else{
            exists[i]=0;
            System.out.println("**********");   
        }
        }   
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        //reg_status.setText("Registration Successful");
        }
        
        switch(count)
        {
            case 4 : af4.setVisible(true);
                    name4.setText(name[4]);
                    place4.setText(place[4]);
                    if(exists[4]==1)
                    {
                        af4.setEnabled(false);
                        if(request_status[4]==0)
                            af4.setText("Friends");
                        else
                            af4.setText("Requested");
                    }
            case 3 : af3.setVisible(true);
                    name3.setText(name[3]);
                    place3.setText(place[3]);
                    if(exists[3]==1)
                    {
                        af3.setEnabled(false);
                        if(request_status[3]==0)
                            af3.setText("Friends");
                        else
                            af3.setText("Requested");
                    }
            case 2 : af2.setVisible(true);
                    name2.setText(name[2]);
                    place2.setText(place[2]);
                    if(exists[2]==1)
                    {
                        af2.setEnabled(false);
                        if(request_status[2]==0)
                            af2.setText("Friends");
                        else
                            af2.setText("Requested");
                    }
            case 1 : af1.setVisible(true);
                    name1.setText(name[1]);
                    place1.setText(place[1]);
                    if(exists[1]==1)
                    {
                        af1.setEnabled(false);
                        if(request_status[1]==0)
                            af1.setText("Friends");
                        else
                            af1.setText("Requested");
                    }
            case 0 : af0.setVisible(true);
                    name0.setText(name[0]);
                    place0.setText(place[0]);
                    
                    
                    if(exists[0]==1)
                    {
                        af0.setEnabled(false);
                        if(request_status[0]==0)
                            af0.setText("Friends");
                        else
                            af0.setText("Requested");
                    }
                
        }
        
    }
    public Search() {
        initComponents();
        af0.setVisible(false);
        af1.setVisible(false);
        af2.setVisible(false);
        af3.setVisible(false);
        af4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name0 = new javax.swing.JLabel();
        place0 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        af0 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        place1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        af1 = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        place2 = new javax.swing.JLabel();
        af2 = new javax.swing.JButton();
        af3 = new javax.swing.JButton();
        af4 = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        place3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        place4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        af0.setText("Send Request");
        af0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af0ActionPerformed(evt);
            }
        });

        af1.setText("jButton2");
        af1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af1ActionPerformed(evt);
            }
        });

        af2.setText("jButton3");
        af2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af2ActionPerformed(evt);
            }
        });

        af3.setText("jButton4");
        af3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af3ActionPerformed(evt);
            }
        });

        af4.setText("jButton5");
        af4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(place0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(af0)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(af1)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(place1))
                            .addComponent(place2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(af2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name4)
                                    .addComponent(place4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(af4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name3)
                                    .addComponent(place3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(af3)))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(af0)
                        .addGap(15, 15, 15)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(af1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(place1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2)
                    .addComponent(af2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(place2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(af3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(af4)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place3)
                        .addGap(18, 18, 18)
                        .addComponent(name4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void af0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af0ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where from_id=? and to_id=?");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[0]);
        
        ResultSet rs=pst1.executeQuery();
        if(rs.next());
            
        PreparedStatement pst=con.prepareStatement("insert into requests (from_id,to_id,date) values (?,?,?)");
        pst.setString(1, id);
        pst.setString(2, requestTo_id[0]);
        pst.setString(3, "2010-10-10");
        
        int status=pst.executeUpdate();
        //reg_status.setText("Registration Successful");
        }
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
        
    }//GEN-LAST:event_af0ActionPerformed

    private void af1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af1ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where from_id=? and to_id=?");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[0]);
        
        ResultSet rs=pst1.executeQuery();
        if(rs.next());
            
        PreparedStatement pst=con.prepareStatement("insert into requests (from_id,to_id,date) values (?,?,?)");
        pst.setString(1, id);
        pst.setString(2, requestTo_id[1]);
        pst.setString(3, "2010-10-10");
        
        int status=pst.executeUpdate();
        //reg_status.setText("Registration Successful");
        }
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_af1ActionPerformed

    private void af2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af2ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where from_id=? and to_id=?");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[0]);
        
        ResultSet rs=pst1.executeQuery();
        if(rs.next());
            
        PreparedStatement pst=con.prepareStatement("insert into requests (from_id,to_id,date) values (?,?,?)");
        pst.setString(1, id);
        pst.setString(2, requestTo_id[2]);
        pst.setString(3, "2010-10-10");
        
        int status=pst.executeUpdate();
        //reg_status.setText("Registration Successful");
        }
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_af2ActionPerformed

    private void af3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af3ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where from_id=? and to_id=?");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[0]);
        
        ResultSet rs=pst1.executeQuery();
        if(rs.next());
            
        PreparedStatement pst=con.prepareStatement("insert into requests (from_id,to_id,date) values (?,?,?)");
        pst.setString(1, id);
        pst.setString(2, requestTo_id[3]);
        pst.setString(3, "2010-10-10");
        
        int status=pst.executeUpdate();
        //reg_status.setText("Registration Successful");
        }
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_af3ActionPerformed

    private void af4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af4ActionPerformed
        // TODO add your handling code here:
        try
        {
        PreparedStatement pst1=con.prepareStatement("select * from requests where from_id=? and to_id=?");
        pst1.setString(1,id);
        pst1.setString(2,requestTo_id[0]);
        
        ResultSet rs=pst1.executeQuery();
        if(rs.next());
            
        PreparedStatement pst=con.prepareStatement("insert into requests (from_id,to_id,date) values (?,?,?)");
        pst.setString(1, id);
        pst.setString(2, requestTo_id[4]);
        pst.setString(3, "2010-10-10");
        
        int status=pst.executeUpdate();
        //reg_status.setText("Registration Successful");
        }
        catch(Exception e)
        {
            //reg_status.setText("User-Id already exists");
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_af4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton af0;
    private javax.swing.JButton af1;
    private javax.swing.JButton af2;
    private javax.swing.JButton af3;
    private javax.swing.JButton af4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel name0;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel place0;
    private javax.swing.JLabel place1;
    private javax.swing.JLabel place2;
    private javax.swing.JLabel place3;
    private javax.swing.JLabel place4;
    // End of variables declaration//GEN-END:variables
}
